
name: Spellcheck README Action

on:
  pull_request:
    branches: [ main, staging ]

jobs:
  spell-check:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@0.33.1
        with:
          source_files: README.md
