
name: Broken Action 3 - Run script

on:
  workflow_dispatch:

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    container:
      image: jhudsl/ottr_python:main

    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run python script
        run: |
          echo "Running python here"
          python3 01-python_test.py
