# Adapted from Alex's Lemonade Stand Foundation https://github.com/AlexsLemonade/refinebio-examples/blob/c43ca1575a96fea547eae0a58fd425c700bc615d/.github/workflows/style-and-sp-check.yml

name: Spell Checker

on:
  pull_request:
    branches: [ staging, main ]

jobs:
  spell-check:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:4.0.2

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install packages
        run: Rscript -e "install.packages(c('spelling'))"

      - name: Run spell check
        id: spell_check_run
        run: |
          results=$(Rscript "utils/spell-check.R")
          echo "::set-output name=sp_chk_results::$results"
          cat spell_check_results.tsv

      - name: Archive spelling errors
        uses: actions/upload-artifact@v2
        with:
          name: spell-check-results
          path: spell_check_results.tsv
