
name: Spellcheck README Action

on:
  pull_request:
    branches: [ main, staging ]

jobs:
  spell-check:
    name: Check spelling
    uses: jhudsl/ottr-reports/.github/workflows/report-maker.yml@main
    with:
      check_type: spelling
      error_min: 3
      gh_pat: secrets.GH_PAT
